# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('creditors', models.ManyToManyField(related_name='creditor', to=settings.AUTH_USER_MODEL)),
                ('debitors', models.ManyToManyField(related_name='debitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
