# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treecount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='creditors',
        ),
        migrations.AddField(
            model_name='expense',
            name='creditor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
