# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treecount', '0003_auto_20160811_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ('date',)},
        ),
    ]
