# Generated by Django 2.0.1 on 2018-01-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treecount', '0004_auto_20160811_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ('-date',)},
        ),
    ]
