# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import treecount.models


class Migration(migrations.Migration):

    dependencies = [
        ('treecount', '0004_auto_20160811_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='expense',
            name='proof',
            field=models.FileField(blank=True, upload_to=treecount.models.name_for_upload, verbose_name='Proof of payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='proof',
            field=models.FileField(blank=True, upload_to=treecount.models.name_for_upload, verbose_name='Proof of payment'),
        ),
    ]
